### ISSUE TITLE
https for n8n-slack integration 

### ISSUE THREAD

**Issue by marianoka** [weslambert/SOARLab#4]
Hi wes!
Is it posible to create a https connection to n8n instead of http? The thing is slack does not accepts http any more for api connections. Or mybe a https -> http redirect.
what do you think?

**Comment by weslambert** [comment]
In which direction? From Slack to n8n? You should be able to use the prefixed path `/n8n/$whatever`. If you are using a self-signed cert, you would need to disable verification from the Slack/client side.

**Comment by marianoka** [comment]
From n8n to slack. When n8n shows the URL to post at the slack application, at this time http is not allowed. After that, I try authenticate using n8n and I get a 503 error

**Comment by weslambert** [comment]
I haven't tested, but you could try adding the following to the n8n init.sls as an environment variable:

`NODE_TLS_REJECT_UNAUTHORIZED=0`

**Comment by marianoka** [comment]
Hi Wes! It was an slack app api issue. There so many options to set up.
Thanks

**Comment by weslambert** [comment]
Sounds good, closing this issue.
