### ISSUE TITLE
Windows Quarentine Artifact is no updating the hive case

### ISSUE THREAD

**Issue by marianoka** [weslambert/SOARLab#5]
hi!
I'm having an issue. Host  quarentine works fine, but I cannot make the hive case update. Checking the velociraptor log (eye icon) I see and weird report:
It shows "Url":"https://192.168.232.15/api/case/qGW4VnsBjMFY7TyXP_Zb" insted of "Url":"https://192.168.232.15/**thehive**/api/case/qGW4VnsBjMFY7TyXP_Zb"
any idea?

**Comment by weslambert** [comment]
Hi @marianoka , what URL did you supply for `TheHiveURL`?

**Comment by marianoka** [comment]
Hi Wes
Thks for your answer. I'm using this
Server_metadata().thehiveurl
In fact, I didn't edit your code.
Thanks

**Comment by marianoka** [comment]
Well.. I did it. I had to hardcode "thehiveurl" and "thehivekey" values. And also, every time a change is made to an artifact you have to relaunch the monitor. I mean, go to "the eye", unselect "windows.Quarentine" Artificat and launch. And then, do the same, selecting windows.Quarentine and then relaunch all the monitors.

**Comment by weslambert** [comment]
Did you actually populate the URL/Key in the server metadata configuration?

**Comment by marianoka** [comment]
No. I dind’t . Which file I have to edit?

 

De: weslambert ***@***.***> 
Enviado el: lunes, 6 de septiembre de 2021 08:48
Para: weslambert/SOARLab ***@***.***>
CC: marianoka ***@***.***>; Mention ***@***.***>
Asunto: Re: [weslambert/SOARLab] Windows Quarentine Artifact is no updating the hive case (#5)

 

Did you actually populate the URL/Key in the server metadata configuration?

**Comment by weslambert** [comment]
You can edit the details by navigating to `$URL/app/index.html#/host/server`.
