### ISSUE TITLE
Velociraptor and SOv2 Client Connection Issue

### ISSUE THREAD

**Issue by ColeVan** [weslambert/SOARLab#6]
Any suggestions or ideas why velociraptor can't connect back to SOv2? Firewalls have been amended on both windows and SOv2 to allow connection.

![image](https://user-images.githubusercontent.com/70167373/132406849-d9901168-4403-4558-9388-39467953e7f7.png)

**Comment by weslambert** [comment]
Have you confirmed traffic is actually hitting port 8000 on the Security Onion box (using Powershell's Test-NetConnection, tcpdump, etc)?

**Comment by ColeVan** [comment]
Here is what I captured. It seems to go out and then dropped. Don't understand why though??? 
![image](https://user-images.githubusercontent.com/70167373/132589764-b7a5b972-07fe-4afd-8921-3060232effb6.png)

**Comment by ColeVan** [comment]
Update: Not sure but I think mylab boxes were not properly making it through my pfsense WAN on 192.168.1.154. I amended my SOv2 firewall rules to include a 192.168.0.0/16 which should cover my 192.168.1.154 WAN IP. This was for testing. IT worked. I should have known. 
![image](https://user-images.githubusercontent.com/70167373/132591591-54c11553-71af-4b2f-8bbc-15fb94ffaff6.png)

**Comment by weslambert** [comment]
My next question was going to be if there was any NATing, etc 😃 . Glad to hear it's working!

**Comment by ColeVan** [comment]
So how to you unquarantine hosts?

**Comment by weslambert** [comment]
You can re-run the quarantine artifact, checking the `RemovePolicy` option.  In newer versions,  there is a button in the GUI.

**Comment by ColeVan** [comment]
That worked! Would love to try out V 0.6.1 new features. Since your repo seems a bit customized how would we go about updating V 0.6.0 to 0.6.1 in Security Onion 2?

**Comment by weslambert** [comment]
I've updated the latest Docker image to v0.6.1.

If you would like to update, the following should work:

(As root):

```
so-velociraptor-stop
docker rmi wlambert/so-velociraptor
so-velociraptor-start
```

Let me know if you have any issues. Thanks!
