### ISSUE TITLE
logtash not starting after installing soar lab

### ISSUE THREAD

**Issue by marianoka** [weslambert/SOARLab#8]
afeter installing soar lab in SO fresh install, logstash is not starting
I'm getting this errors
![imagen](https://user-images.githubusercontent.com/9213379/138597604-80c5dab1-c97d-42f1-99a4-e0050f0e71fc.png)
![imagen](https://user-images.githubusercontent.com/9213379/138597625-8020c5f0-21d4-4977-b891-65f0877c9514.png)
![imagen](https://user-images.githubusercontent.com/9213379/138597637-f8a6b563-a49e-4f42-ab24-9619a184ef75.png)

**Comment by weslambert** [comment]
I just tried this from an upgrade to 2.3.80 (before installing SOARLab) without any issue:

![image](https://user-images.githubusercontent.com/16829864/138785369-107f830d-633e-4d11-8182-c11dd547c252.png)

You might want to try re-downloading the ISO and installing fresh again.
